language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
  licenses:
      - android-sdk-license-5be876d5

branches:
  only:
    - master

jdk: openjdk7

notifications:
  email: false

install: gradle clean build

script: gradle check
